const allFacts = [
  [
    'Earth is approximately 4.54 billion years old.',
    'Earth is not a perfect sphere. It’s slightly flattened at the poles and bulging at the equator due to its rotation, making it an oblate spheroid.',
    'Earth’s atmosphere is made up of 78% nitrogen, 21% oxygen, and traces of other gases, such as argon and carbon dioxide.',
    'About 71% of Earth’s surface is covered by water, with the remaining 29% being land.',
    'Earth has a magnetic field generated by movements in its molten outer core. This field protects us from harmful solar and cosmic radiation.',
  ],
  [
    'Mars is often called the "Red Planet" due to its reddish appearance, caused by iron oxide (rust) on its surface.',
    'Mars is about half the size of Earth, with a diameter of approximately 6,779 kilometers (4,212 miles).',
    "Mars has only about 38% of Earth's gravity, meaning you would weigh significantly less on Mars.",
    'The atmosphere of Mars is very thin, composed mostly of carbon dioxide (95%), with traces of nitrogen and argon. It’s not breathable for humans.',
    'Mars is much colder than Earth, with an average surface temperature of about -80°F (-60°C). Temperatures can drop as low as -195°F (-125°C) near the poles during winter.',
  ],
  [
    'Mercury is the closest planet to the Sun, orbiting at an average distance of about 36 million miles (58 million kilometers).',
    "Mercury is the smallest planet in the solar system, with a diameter of 4,880 kilometers (3,032 miles), making it only slightly larger than Earth's Moon.",
    'Mercury experiences drastic temperature swings. During the day, surface temperatures can reach up to 800°F (430°C), while at night, they can plummet to -290°F (-180°C) because it has almost no atmosphere to retain heat.',
    'Mercury has a very thin exosphere (not a true atmosphere) made of oxygen, sodium, hydrogen, helium, and potassium. It can’t support life as we know it.',
    'Mercury has the shortest orbit around the Sun, completing a revolution in just 88 Earth days. However, a day (rotation) on Mercury takes 59 Earth days.',
  ],
  [
    'Venus is the second planet from the Sun, orbiting at an average distance of about 67 million miles (108 million kilometers).',
    'Venus is often called Earth’s "sister planet" because it’s nearly the same size, with a diameter of 12,104 kilometers (7,521 miles), just slightly smaller than Earth.',
    'Venus’s atmosphere is mostly carbon dioxide (96.5%), with clouds of sulfuric acid. This dense atmosphere traps heat and creates enormous surface pressure—about 92 times that of Earth’s, equivalent to being 3,000 feet underwater.',
    'Venus rotates in the opposite direction to most planets in the solar system, a phenomenon known as "retrograde rotation." It spins from east to west, meaning the Sun rises in the west and sets in the east.',
    'A day on Venus (one full rotation) is longer than its year. Venus takes 243 Earth days to complete one rotation, while its orbit around the Sun takes 225 Earth days.',
  ],
  [
    'Jupiter is the largest planet in the solar system, with a diameter of about 142,984 kilometers (88,846 miles).',
    'Jupiter is primarily composed of hydrogen (about 90%) and helium (about 10%), and it lacks a solid surface.',
    'The Great Red Spot on Jupiter is a massive storm that has been raging for at least 400 years.',
    'Jupiter has the fastest rotation of any planet, completing one rotation in about 10 hours.',
    'Jupiter has the strongest magnetic field of all the planets, about 14 times stronger than Earth’s.',
  ],
  [
    'Saturn is the second largest planet in the solar system, with a diameter of about 120,536 kilometers (74,898 miles).',
    'Saturn is famous for its stunning ring system, which is the most extensive and visible in the solar system.',
    'Saturn is a gas giant, primarily composed of hydrogen (96%) and helium (3%).',
    'Saturn is the least dense planet, and it would float in water if a large enough body of water existed.',
    'A day on Saturn lasts about 10.7 hours due to its fast rotation.',
  ],
  [
    "Uranus is classified as an 'ice giant' because it is primarily composed of icy materials like water, ammonia, and methane.",
    'Uranus orbits the Sun at a distance of about 1.8 billion miles (2.9 billion kilometers).',
    'Uranus rotates on its side, with an axial tilt of about 98 degrees, causing extreme seasons.',
    'The blue-green color of Uranus is due to methane in its atmosphere, which absorbs red light and reflects blue.',
    'Uranus is one of the coldest planets, with temperatures dropping as low as -371°F (-224°C).',
  ],
  [
    'Neptune is the eighth planet in the solar system, located about 4.5 billion kilometers (2.8 billion miles) from the Sun.',
    'Neptune is an ice giant, with an atmosphere of hydrogen, helium, and methane, and icy materials deep inside.',
    'Neptune’s blue color comes from methane in its atmosphere, which reflects blue light.',
    'Neptune has the strongest winds in the solar system, reaching up to 1,200 miles per hour (2,000 kilometers per hour).',
    'Neptune is one of the coldest planets, with temperatures around -373°F (-225°C).',
  ],
];

export { allFacts };
